### PR TITLE
Editor: Expand Hierarchy to current selection.

### PR DESCRIPTION
**Pull request by TrevorCash**

### CODE REVIEW

**Comment by TrevorCash** [comment]
what less white space?

**Comment by rokups** [comment]
Nah, `{` should be on the new line.

**Comment by rokups** [comment]
Im nitpicky but could you please make it also a single commit? ;)

**Comment by TrevorCash** [comment]
Merge it yourself.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by TrevorCash** [comment]
ok should be one branch now

**Pull request merged**
