### PR TITLE
Updates to Timer and HTimer

### PR DESCRIPTION
**Pull request by TrevorCash**

### CODE REVIEW

**Comment by rokups** [comment]
Did not notice PRs before, sorry. Any reason why you are submitting them here instead of upstream Urho3D? I do appreciate the contributions, but goal of this fork is to remain compatible with upstream as much as possible. Besides you worked on angelscript bingins as well, and this fork has all bindings removed. Maybe you really meant submitting PRs to https://github.com/urho3d/Urho3D ?

**Comment by TrevorCash** [comment]
Hi Rokups,

I did submit this pr to upstream. I guess they seemed slow to merge and I was trigger happy.

I love seeing all your features!

Do you actively trim out script bindinds on this fork if there is an upstream change?   Ive personally removed script components from my project after realizing what a slowdown it was to productivity.

Best, Trevor


Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by rokups** [comment]
I removed bindings myself as i totally hate dealing with them :)

Awesome that your PR went upstream! Less maintenance burden overhere ;) I will close this PR then, will pull it in when upstream accepts it as i see they are OK with PR (but not tabs :p )

**Comment by TrevorCash** [comment]
Ah thanks I guess it is still some white-space fixes, will look into that!

**Comment by TrevorCash** [comment]
Also is the build process for this fork different than upstream?  I noticed the cmake .bat scripts are not in the root directory.

**Comment by rokups** [comment]
Yes, i replaced build system completely, making new one follow all the modern cmake practices. In some cases it still is inferior, but in some other - superior. And ofc easier to work with

**Pull request closed without merging**
