### PR TITLE
Fix GLEW Linker errors on Shared Configuration closes #22

### LINKED ISSUE #22: linker errors related to glfw when building with shared third party libs
With: -DBUILD_SHARED_LIBS=ON On Visual Studio 2017 Building Urho3D Project:
image

### PR DESCRIPTION
**Pull request by TrevorCash**

### CODE REVIEW

**Comment by rokups** [comment]
This breaks MacOS build, also please remove those extra blank lines.

**Comment by TrevorCash** [comment]
how do you suggest fixing it?

**Comment by rokups** [comment]
Idk. It complains about missing symbols. `GLEW_MX` define looks like changes behaviour around functions involved in the error. Maybe try defining that for shared builds.

**Comment by rokups** [comment]
Closing this one as we had thirdparty lib rework where now they are always static libs and we also got your fork building. :)

**Pull request closed without merging**
