### PR TITLE
Editor: Add NormalizeNodeChildrenPosition function.

### PR DESCRIPTION
**Pull request by TrevorCash**
Adds a useful tool to move all immediate children of a node to the parent node's center.

### CODE REVIEW

**Comment by rokups** [comment]
Is this functionality really needed that often? One node can be moved to the center of it's parent by resetting local transform.

@Alan-FGR what do you think of this?

**Comment by TrevorCash** [comment]
It's more useful when your working with groups of nodes and you want to transform or duplicate the groups.  The reason I added it was to groups an existing "loop d loop" shape that I wanted to consisted of 50+ shapes.  And rotate and duplicate it.

**Comment by Alan-FGR** [comment]
Well, I think this could be useful in many situations, but I think it would be nice to have a version that doesn't translate the children to the parent but just places the parent in the center of the children objects without changing the children positions. It would be useful especially when you're using the scenegraph hierarchy to organize things, so you can add a parent node at zero for the root, then place the children objects on the scene, and if they're concentrated far away from zero  you might want to have the parent center close to them. Now whether using the scenegraph for organization should be recommended is arguable ofc. In Urho at least when it comes to perf it doesn't matter much because transform propagation is cached anyway although iirc root skips that. It's a natural thing though, and other engines recommend that. It makes sense for the user although there are technical implications.
In any case, this is very specific and advanced functionality so it could be hidden behind some advanced menu (or drawer) or something... also, allowing the user to choose whether the aabb or just the origins should be used could be handy in some cases (but don't bother until we know a real use case).
@rokups I'll be back on gitter *tonight* :trollface:

**Comment by rokups** [comment]
> *tonight*
@Alan-FGR shit you got me :trollface:

**Comment by rokups** [comment]
@TrevorCash i am unsure about this. Indeed this sounds like a very specialized utility. Also menu item name is confusing (or maybe i am just not aware of these terms). I had to experiment with this option to actually understand what it does. I will not merge this in order to keep things simple and not clutter UI with things people will hardly ever need.

Idea: this functionality sounds like could be a great plugin in a form of single C# script file which engine would compile on the fly. Of course this is not possible yet.

Even though i did not merge this, thanks for the PR anyway!

**Pull request closed without merging**
